### ISSUE TITLE
Add javax.annotation:annotation-api to MicroProfile BOM

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-bom#31]
CDI Implementations need javax.annotation to work, so it has to be there.  In addition, the JWT API will be requiring its use, we may as well add it to ensure its always present.

**Comment by kwsutter** [comment]
Resolving via PR #32

**Comment by kwsutter** [comment]
@johnament Are you okay with Closing this Issue?  I don't want to presume that the PR #32 solved the problem since you wrote the Issue.  Thanks.

**Comment by johnament** [comment]
Looks done to me.
