### ISSUE TITLE
Missing tags for 1.4/2.0

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-bom#76]
There are missing tags/GH release for 1.4 and 2.x 

cc) @jclingan @kwsutter

**Comment by kenfinnigan** [comment]
They were moved to https://github.com/eclipse/microprofile for those releases

**Comment by pavolloffay** [comment]
It would be good to add a note in the readme about the change

**Comment by pavolloffay** [comment]
https://github.com/eclipse/microprofile-bom/pull/77
